"""AUTO-GENERATED by scripts/tools/gen_limits.py — DO NOT EDIT BY HAND.

Every number here was read out of supercat_server, not out of a document.
Regenerate with:

    python scripts/tools/gen_limits.py --server-root <path-to-supercat_server>

and verify with `--check`, which the test suite runs whenever the source tree
is available. See IMPLEMENTATION_PLAN.md 4.1 for why transcribing these is
a build error rather than a style choice.
"""

GENERATED_AT = '2026-07-27T20:13:44Z'
SOURCE_REPO = 'supercat_server'
SOURCE_GIT_SHA = 'd4a0e7d408fba6917ac5e685cd21e54c5ecd801d'

# path within supercat_server -> short content hash at generation time
SOURCE_FILES = {
    'app/models/customer.rb': '92075c54e1ee',
    'app/models/file_reader.rb': 'c4af550aec9a',
    'app/models/importer/customer_importer.rb': 'a78a3fe11b0f',
    'app/models/importer/option_group_importer.rb': 'f7675da551ef',
    'app/models/importer/shipping_location_importer.rb': '413fd27324c4',
    'app/models/inventory.rb': 'c944b1a4ab69',
    'app/models/option.rb': '3fd839aa4d0f',
    'app/models/option_group.rb': 'bb42a7152250',
    'app/models/product.rb': '54dc5fd44be4',
    'app/models/shipping_location.rb': '3cf9b8a3c16e',
    'app/models/taxonomy.rb': 'a3a6efbd8e3f',
    'app/services/importer/inventory_importer.rb': '1d85d4b94c15',
    'app/services/importer/line_data_validator.rb': 'a95b3b789135',
    'app/services/importer/option_importer.rb': '28842d61e87e',
    'app/services/importer/product_importer.rb': '27b5f43a18ba',
    'app/services/importer/product_importer_lib/cdn_image_sync.rb': 'dd2d39114e4e',
}

# file -> csv header (lowercase) -> limit metadata.
#   tier 'error'    -> the importer raises a validation error; the row is rejected
#   tier 'truncate' -> the importer warns and silently truncates (ATTRS_TO_TRUNCATE)
LIMITS = {
    'products.csv': {
        'baseitemcode': {
            'limit': 40,
            'tier': 'error',
            'attr': 'item_number',
            'model': 'Product',
        },
        'categorycode': {
            'limit': 255,
            'tier': 'error',
            'attr': 'category_code',
            'model': 'Product',
        },
        'collectioncode': {
            'limit': 255,
            'tier': 'error',
            'attr': 'collection_code',
            'model': 'Product',
        },
        'dimensions': {
            'limit': 50,
            'tier': 'truncate',
            'attr': 'product_dimensions_in',
            'model': 'Product',
        },
        'discountpricelevelcode': {
            'limit': 255,
            'tier': 'error',
            'attr': 'discount_price_level_code',
            'model': 'Product',
        },
        'features': {
            'limit': 50,
            'tier': 'truncate',
            'attr': 'features',
            'model': 'Product',
        },
        'longdesc': {
            'limit': 255,
            'tier': 'truncate',
            'attr': 'long_description',
            'model': 'Product',
        },
        'materials': {
            'limit': 50,
            'tier': 'truncate',
            'attr': 'materials_description',
            'model': 'Product',
        },
        'mediumdesc': {
            'limit': 255,
            'tier': 'truncate',
            'attr': 'plist_description',
            'model': 'Product',
        },
        'shipweight': {
            'limit': 8,
            'tier': 'error',
            'attr': 'shipping_weight',
            'model': 'Product',
        },
        'shortdesc': {
            'limit': 255,
            'tier': 'truncate',
            'attr': 'short_description',
            'model': 'Product',
        },
        'tradenamecode': {
            'limit': 255,
            'tier': 'error',
            'attr': 'trade_name_code',
            'model': 'Product',
        },
        'upctype': {
            'limit': 255,
            'tier': 'error',
            'attr': 'upc_type',
            'model': 'Product',
        },
        'upcvalue': {
            'limit': 255,
            'tier': 'error',
            'attr': 'upc_value',
            'model': 'Product',
        },
    },
    'customers.csv': {
        'billtoaddress1': {
            'limit': 60,
            'tier': 'error',
            'attr': 'billing_address1',
            'model': 'Customer',
        },
        'billtoaddress2': {
            'limit': 60,
            'tier': 'error',
            'attr': 'billing_address2',
            'model': 'Customer',
        },
        'billtoaddress3': {
            'limit': 60,
            'tier': 'error',
            'attr': 'billing_address3',
            'model': 'Customer',
        },
        'billtocity': {
            'limit': 60,
            'tier': 'error',
            'attr': 'billing_city',
            'model': 'Customer',
        },
        'billtocode': {
            'limit': 20,
            'tier': 'error',
            'attr': 'code',
            'model': 'Customer',
        },
        'billtocountry': {
            'limit': 60,
            'tier': 'error',
            'attr': 'billing_country',
            'model': 'Customer',
        },
        'billtoname': {
            'limit': 60,
            'tier': 'error',
            'attr': 'name',
            'model': 'Customer',
        },
        'billtopostcode': {
            'limit': 20,
            'tier': 'error',
            'attr': 'billing_post_code',
            'model': 'Customer',
        },
        'billtoshortname': {
            'limit': 25,
            'tier': 'error',
            'attr': 'shortname',
            'model': 'Customer',
        },
        'billtostate': {
            'limit': 60,
            'tier': 'error',
            'attr': 'billing_state',
            'model': 'Customer',
        },
        'buyeremail': {
            'limit': 100,
            'tier': 'error',
            'attr': 'buyer_email',
            'model': 'Customer',
        },
        'buyerfax': {
            'limit': 25,
            'tier': 'error',
            'attr': 'buyer_fax',
            'model': 'Customer',
        },
        'buyerfirstname': {
            'limit': 25,
            'tier': 'error',
            'attr': 'buyer_first_name',
            'model': 'Customer',
        },
        'buyerlastname': {
            'limit': 25,
            'tier': 'error',
            'attr': 'buyer_last_name',
            'model': 'Customer',
        },
        'buyerphone': {
            'limit': 25,
            'tier': 'error',
            'attr': 'buyer_phone',
            'model': 'Customer',
        },
        'defaultpricecode': {
            'limit': 30,
            'tier': 'error',
            'attr': 'default_price_code',
            'model': 'Customer',
        },
        'distributioncenter': {
            'limit': 60,
            'tier': 'error',
            'attr': 'distribution_source',
            'model': 'Customer',
        },
        'distributionsource': {
            'limit': 60,
            'tier': 'error',
            'attr': 'distribution_source',
            'model': 'Customer',
        },
        'terms': {
            'limit': 30,
            'tier': 'error',
            'attr': 'terms',
            'model': 'Customer',
        },
        'carrier': {
            'limit': 255,
            'tier': 'error',
            'attr': 'carrier',
            'model': 'ShippingLocation',
        },
        'shipinstructions': {
            'limit': 255,
            'tier': 'error',
            'attr': 'ship_instructions',
            'model': 'ShippingLocation',
        },
        'shiptoaddress1': {
            'limit': 60,
            'tier': 'error',
            'attr': 'address1',
            'model': 'ShippingLocation',
        },
        'shiptoaddress2': {
            'limit': 60,
            'tier': 'error',
            'attr': 'address2',
            'model': 'ShippingLocation',
        },
        'shiptoaddress3': {
            'limit': 60,
            'tier': 'error',
            'attr': 'address3',
            'model': 'ShippingLocation',
        },
        'shiptocity': {
            'limit': 60,
            'tier': 'error',
            'attr': 'city',
            'model': 'ShippingLocation',
        },
        'shiptocode': {
            'limit': 255,
            'tier': 'error',
            'attr': 'code',
            'model': 'ShippingLocation',
        },
        'shiptocountry': {
            'limit': 60,
            'tier': 'error',
            'attr': 'country',
            'model': 'ShippingLocation',
        },
        'shiptoemail': {
            'limit': 100,
            'tier': 'error',
            'attr': 'email',
            'model': 'ShippingLocation',
        },
        'shiptophone': {
            'limit': 25,
            'tier': 'error',
            'attr': 'phone',
            'model': 'ShippingLocation',
        },
        'shiptopostcode': {
            'limit': 20,
            'tier': 'error',
            'attr': 'post_code',
            'model': 'ShippingLocation',
        },
        'shiptostate': {
            'limit': 60,
            'tier': 'error',
            'attr': 'state',
            'model': 'ShippingLocation',
        },
    },
    'inventory.csv': {
        'option1': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option1',
            'model': 'Inventory',
        },
        'option10': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option10',
            'model': 'Inventory',
        },
        'option11': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option11',
            'model': 'Inventory',
        },
        'option12': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option12',
            'model': 'Inventory',
        },
        'option13': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option13',
            'model': 'Inventory',
        },
        'option14': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option14',
            'model': 'Inventory',
        },
        'option15': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option15',
            'model': 'Inventory',
        },
        'option16': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option16',
            'model': 'Inventory',
        },
        'option17': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option17',
            'model': 'Inventory',
        },
        'option18': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option18',
            'model': 'Inventory',
        },
        'option19': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option19',
            'model': 'Inventory',
        },
        'option2': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option2',
            'model': 'Inventory',
        },
        'option20': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option20',
            'model': 'Inventory',
        },
        'option3': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option3',
            'model': 'Inventory',
        },
        'option4': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option4',
            'model': 'Inventory',
        },
        'option5': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option5',
            'model': 'Inventory',
        },
        'option6': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option6',
            'model': 'Inventory',
        },
        'option7': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option7',
            'model': 'Inventory',
        },
        'option8': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option8',
            'model': 'Inventory',
        },
        'option9': {
            'limit': 15,
            'tier': 'error',
            'attr': 'option9',
            'model': 'Inventory',
        },
    },
    'options.csv': {
        'code': {
            'limit': 15,
            'tier': 'error',
            'attr': 'code',
            'model': 'Option',
        },
        'name': {
            'limit': 50,
            'tier': 'error',
            'attr': 'name',
            'model': 'Option',
        },
    },
    'option_groups.csv': {
        'code': {
            'limit': 15,
            'tier': 'error',
            'attr': 'code',
            'model': 'OptionGroup',
        },
        'name': {
            'limit': 50,
            'tier': 'error',
            'attr': 'name',
            'model': 'OptionGroup',
        },
    },
}

# Headers the importer treats as fatal-if-absent.
REQUIRED_HEADERS = {
    'products.csv': ['baseitemcode'],
    'inventory.csv': ['baseitemcode'],
    'options.csv': ['code', 'name'],
    'option_groups.csv': ['code', 'name', 'options'],
    'customers.csv': ['billtoaddress1', 'billtocity', 'billtocode', 'billtoname', 'billtopostcode', 'billtostate', 'defaultpricecode'],
    'customers.csv:shipto': ['shiptoaddress1', 'shiptocity'],
}

# Thresholds that live in importer logic rather than ATTR_LENGTHS. These warn.
ADVISORY_LIMITS = {
    'customers.csv': {
        'billtocode': {
            'limit': 15,
            'note': 'importer logs :warning above 15; Customer::ATTR_LENGTHS errors above 20',
            'source': 'app/models/importer/customer_importer.rb',
        },
    },
}

# CdnImageSync accepts a URL only if BOTH gates pass (4.7).
IMAGE_RULES = {
    'content_types': ['image/jpeg', 'image/jpg'],
    'extensions': ['.jpeg', '.jpg'],
    'filename_regex': '^[^/()]*$',
}

# The fatal a UTF-8 BOM produces via LineDataValidator#validate_header (4.8),
# which reads the header with CSV.open and no 'bom|' prefix while row parsing
# uses FileReader.each_line with encoding 'bom|utf-8' and strips it.
BOM_FATAL_MESSAGE = 'Column {column} is missing and is required'
