#!/usr/bin/env python3
"""Extract a client script's lookup tables into mapping TOML — once, as data.

Transcribing a table by hand is a build error, not a style choice (the same
rule that keeps field limits in `preflight/limits_generated.py`). Legrand's
CATEGORY_REMAP alone is 47 entries; a single mistyped key silently reroutes a
product's taxonomy, and the iPad label IS the string you ship.

So the tables are READ OUT of `build_ecat_files.py` and written to
`tables.toml`. After this runs the mapping is standalone: the script can be
discarded, which is exactly what Phase 2's acceptance test requires.

usage: extract_tables.py <build_ecat_files.py> <out tables.toml>
"""

import importlib.util
import os
import sys

# The constants that are client DECISIONS (which spelling, which category rolls
# up to which collection) rather than rules. Rules belong in ecatlib; these
# belong in the mapping.
TABLES = [
    ('category_fixes', 'CATEGORY_FIXES'),
    ('category_remap', 'CATEGORY_REMAP'),
    ('category_to_collection', 'CATEGORY_TO_COLLECTION'),
    ('finish_fixes', 'FINISH_FIXES'),
    ('finish_overrides', 'FINISH_OVERRIDES'),
    ('product_name_fixes', 'PRODUCT_NAME_FIXES'),
]


def toml_escape(s):
    out = s.replace('\\', '\\\\').replace('"', '\\"')
    return out.replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t')


def load_module(path):
    spec = importlib.util.spec_from_file_location('_client_build', path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    script, out_path = sys.argv[1], sys.argv[2]
    mod = load_module(os.path.abspath(script))

    lines = [
        '# Lookup tables for the Legrand products.csv mapping.',
        '#',
        '# GENERATED by mapping/extract_tables.py from build_ecat_files.py.',
        '# Do not hand-edit: re-run the extractor, or promote a rule into ecatlib.',
        '# These are client DECISIONS (spellings, taxonomy roll-up), not rules.',
        '#',
        '# source: %s' % os.path.basename(script),
        '',
    ]
    counts = {}
    for name, const in TABLES:
        table = getattr(mod, const)
        counts[name] = len(table)
        lines.append('# %s -- %d entries, from %s' % (name, len(table), const))
        lines.append('[%s]' % name)
        for k, v in table.items():
            lines.append('"%s" = "%s"' % (toml_escape(str(k)), toml_escape(str(v))))
        lines.append('')

    with open(out_path, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines))

    print('wrote %s' % out_path)
    for name, n in counts.items():
        print('  %-24s %3d entries' % (name, n))
    return 0


if __name__ == '__main__':
    sys.exit(main())
