#!/usr/bin/env python3
"""Extract 111Mercer's taxonomy roll-up into mapping TOML — once, as data.

mer's taxonomy is not in a script; it is in the LIVE BUILD. Ten source
`Collection` strings roll up to four CollectionCodes and five CategoryCodes,
and those groupings are client decisions already made and confirmed with the
client. Reading them back out beats retyping them: Auto-Create means whatever
string ships BECOMES the iPad label, so a typo here is a relabelled collection
on a rep's iPad, not a build error someone catches.

Refuses to write if any source collection maps to more than one target, because
that would mean the roll-up is not a function and the mapping cannot express it.

usage: extract_mer_tables.py <111Mercer dir> <out tables.toml>
"""

import collections
import csv
import os
import sys


def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    root, out_path = sys.argv[1], sys.argv[2]
    raw = {(r['Name'] or '').strip(): r for r in csv.DictReader(
        open(os.path.join(root, 'Source Data', '111Mercer-ItemExport .csv'),
             encoding='utf-8-sig'))}
    live = list(csv.DictReader(
        open(os.path.join(root, 'Import Files', 'products.csv'),
             encoding='utf-8-sig')))

    coll = collections.defaultdict(collections.Counter)
    cat = collections.defaultdict(collections.Counter)
    for lr in live:
        code = lr['BaseItemCode'].strip()
        src = raw[code]['Collection'].strip()
        coll[src][lr['CollectionCodes'].strip()] += 1
        if not code.endswith('-S'):
            cat[src][lr['CategoryCodes'].strip()] += 1

    ambiguous = ([k for k, v in coll.items() if len(v) > 1] +
                 [k for k, v in cat.items() if len(v) > 1])
    if ambiguous:
        print('REFUSING: these source collections map to more than one target, '
              'so the roll-up is not a function:')
        for k in ambiguous:
            print('   %r -> %r' % (k, dict(coll.get(k) or cat.get(k))))
        return 1

    lines = [
        '# 111 Mercer (mer) -- taxonomy tables for products.csv',
        '#',
        '# GENERATED by mapping/extract_mer_tables.py from the CURRENT LIVE BUILD',
        '# (Import Files/products.csv, imported and in production). These are the',
        '# client taxonomy DECISIONS already made and confirmed with the client,',
        '# read back out rather than re-invented.',
        '#',
        '# Auto-Create: whatever string is here BECOMES the iPad label. Never ship',
        '# internal codes.',
        '',
        '# raw `Collection` -> CollectionCodes  (%d entries)' % len(coll),
        '[collection_codes]',
    ]
    for k in sorted(coll):
        lines.append('"%s" = "%s"' % (esc(k), esc(coll[k].most_common(1)[0][0])))
    lines += ['',
              '# raw `Collection` -> CategoryCodes for NON-sample SKUs (%d entries).'
              % len(cat),
              '# Sample SKUs take a literal category instead -- see products.toml.',
              '[category_codes]']
    for k in sorted(cat):
        lines.append('"%s" = "%s"' % (esc(k), esc(cat[k].most_common(1)[0][0])))

    with open(out_path, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines) + '\n')
    print('wrote %s' % out_path)
    print('  collection_codes  %d entries' % len(coll))
    print('  category_codes    %d entries' % len(cat))
    return 0


if __name__ == '__main__':
    sys.exit(main())
