#!/usr/bin/env python3
"""Write fresh Postgres cache files from live MCP data collected 2026-04-07."""
import pandas as pd
from pathlib import Path

CACHE_DIR = Path(__file__).parent / "cache"

# ---- pg_imp ----
imp_data = [
    {'org_shortname': 'aa', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'abol', 'total_imports_90d': 37, 'successful_imports_90d': 37, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'acsd', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'afx', 'total_imports_90d': 35, 'successful_imports_90d': 34, 'import_success_rate': 0.9714, 'last_import_had_errors': False},
    {'org_shortname': 'ah', 'total_imports_90d': 2539, 'successful_imports_90d': 2483, 'import_success_rate': 0.9779, 'last_import_had_errors': False},
    {'org_shortname': 'ali', 'total_imports_90d': 223, 'successful_imports_90d': 150, 'import_success_rate': 0.6726, 'last_import_had_errors': False},
    {'org_shortname': 'all', 'total_imports_90d': 27, 'successful_imports_90d': 27, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'am', 'total_imports_90d': 5, 'successful_imports_90d': 2, 'import_success_rate': 0.4, 'last_import_had_errors': False},
    {'org_shortname': 'ap', 'total_imports_90d': 99, 'successful_imports_90d': 74, 'import_success_rate': 0.7475, 'last_import_had_errors': False},
    {'org_shortname': 'arl', 'total_imports_90d': 7, 'successful_imports_90d': 7, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'art', 'total_imports_90d': 130, 'successful_imports_90d': 35, 'import_success_rate': 0.2692, 'last_import_had_errors': True},
    {'org_shortname': 'asi', 'total_imports_90d': 1121, 'successful_imports_90d': 1104, 'import_success_rate': 0.9848, 'last_import_had_errors': False},
    {'org_shortname': 'ati', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'bc', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': True},
    {'org_shortname': 'bcf', 'total_imports_90d': 377, 'successful_imports_90d': 362, 'import_success_rate': 0.9602, 'last_import_had_errors': False},
    {'org_shortname': 'bei', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'bi', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': True},
    {'org_shortname': 'big', 'total_imports_90d': 83, 'successful_imports_90d': 80, 'import_success_rate': 0.9639, 'last_import_had_errors': False},
    {'org_shortname': 'blh', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'bmc', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'bp', 'total_imports_90d': 233, 'successful_imports_90d': 114, 'import_success_rate': 0.4893, 'last_import_had_errors': True},
    {'org_shortname': 'bri', 'total_imports_90d': 542, 'successful_imports_90d': 448, 'import_success_rate': 0.8266, 'last_import_had_errors': False},
    {'org_shortname': 'bsc', 'total_imports_90d': 37, 'successful_imports_90d': 24, 'import_success_rate': 0.6486, 'last_import_had_errors': False},
    {'org_shortname': 'cc', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': True},
    {'org_shortname': 'cci', 'total_imports_90d': 1306, 'successful_imports_90d': 849, 'import_success_rate': 0.6501, 'last_import_had_errors': False},
    {'org_shortname': 'cf', 'total_imports_90d': 155, 'successful_imports_90d': 155, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'cfg', 'total_imports_90d': 57, 'successful_imports_90d': 30, 'import_success_rate': 0.5263, 'last_import_had_errors': True},
    {'org_shortname': 'cl', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'clc', 'total_imports_90d': 138, 'successful_imports_90d': 135, 'import_success_rate': 0.9783, 'last_import_had_errors': False},
    {'org_shortname': 'clli', 'total_imports_90d': 3430, 'successful_imports_90d': 3422, 'import_success_rate': 0.9977, 'last_import_had_errors': False},
    {'org_shortname': 'clm', 'total_imports_90d': 1015, 'successful_imports_90d': 963, 'import_success_rate': 0.9488, 'last_import_had_errors': False},
    {'org_shortname': 'cst', 'total_imports_90d': 1045, 'successful_imports_90d': 917, 'import_success_rate': 0.8775, 'last_import_had_errors': False},
    {'org_shortname': 'da', 'total_imports_90d': 249, 'successful_imports_90d': 148, 'import_success_rate': 0.5944, 'last_import_had_errors': False},
    {'org_shortname': 'dals', 'total_imports_90d': 1, 'successful_imports_90d': 0, 'import_success_rate': 0.0, 'last_import_had_errors': True},
    {'org_shortname': 'dccl', 'total_imports_90d': 184, 'successful_imports_90d': 122, 'import_success_rate': 0.663, 'last_import_had_errors': True},
    {'org_shortname': 'df', 'total_imports_90d': 65, 'successful_imports_90d': 65, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'dpl', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': True},
    {'org_shortname': 'dri', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'dws', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'ebc', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': True},
    {'org_shortname': 'eglo', 'total_imports_90d': 394, 'successful_imports_90d': 179, 'import_success_rate': 0.4543, 'last_import_had_errors': True},
    {'org_shortname': 'eglo_can', 'total_imports_90d': 365, 'successful_imports_90d': 313, 'import_success_rate': 0.8575, 'last_import_had_errors': False},
    {'org_shortname': 'el', 'total_imports_90d': 7312, 'successful_imports_90d': 7299, 'import_success_rate': 0.9982, 'last_import_had_errors': False},
    {'org_shortname': 'eli', 'total_imports_90d': 253, 'successful_imports_90d': 208, 'import_success_rate': 0.8221, 'last_import_had_errors': False},
    {'org_shortname': 'elk', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': True},
    {'org_shortname': 'et2', 'total_imports_90d': 14, 'successful_imports_90d': 10, 'import_success_rate': 0.7143, 'last_import_had_errors': True},
    {'org_shortname': 'etl', 'total_imports_90d': 229, 'successful_imports_90d': 220, 'import_success_rate': 0.9607, 'last_import_had_errors': False},
    {'org_shortname': 'fal', 'total_imports_90d': 18, 'successful_imports_90d': 7, 'import_success_rate': 0.3889, 'last_import_had_errors': True},
    {'org_shortname': 'fc', 'total_imports_90d': 937, 'successful_imports_90d': 654, 'import_success_rate': 0.698, 'last_import_had_errors': False},
    {'org_shortname': 'fcc', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'fms', 'total_imports_90d': 641, 'successful_imports_90d': 323, 'import_success_rate': 0.5039, 'last_import_had_errors': False},
    {'org_shortname': 'frh', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'fsf', 'total_imports_90d': 406, 'successful_imports_90d': 393, 'import_success_rate': 0.968, 'last_import_had_errors': False},
    {'org_shortname': 'gb', 'total_imports_90d': 290, 'successful_imports_90d': 290, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'gc', 'total_imports_90d': 99, 'successful_imports_90d': 84, 'import_success_rate': 0.8485, 'last_import_had_errors': False},
    {'org_shortname': 'gcl', 'total_imports_90d': 55, 'successful_imports_90d': 38, 'import_success_rate': 0.6909, 'last_import_had_errors': True},
    {'org_shortname': 'gg', 'total_imports_90d': 291, 'successful_imports_90d': 285, 'import_success_rate': 0.9794, 'last_import_had_errors': False},
    {'org_shortname': 'gh', 'total_imports_90d': 1344, 'successful_imports_90d': 1334, 'import_success_rate': 0.9926, 'last_import_had_errors': False},
    {'org_shortname': 'gl', 'total_imports_90d': 505, 'successful_imports_90d': 465, 'import_success_rate': 0.9208, 'last_import_had_errors': False},
    {'org_shortname': 'gsa', 'total_imports_90d': 234, 'successful_imports_90d': 228, 'import_success_rate': 0.9744, 'last_import_had_errors': False},
    {'org_shortname': 'hatl', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'hcan', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': True},
    {'org_shortname': 'heb', 'total_imports_90d': 623, 'successful_imports_90d': 413, 'import_success_rate': 0.6629, 'last_import_had_errors': True},
    {'org_shortname': 'hf', 'total_imports_90d': 134, 'successful_imports_90d': 44, 'import_success_rate': 0.3284, 'last_import_had_errors': False},
    {'org_shortname': 'hfg', 'total_imports_90d': 260, 'successful_imports_90d': 170, 'import_success_rate': 0.6538, 'last_import_had_errors': False},
    {'org_shortname': 'hh', 'total_imports_90d': 148, 'successful_imports_90d': 139, 'import_success_rate': 0.9392, 'last_import_had_errors': False},
    {'org_shortname': 'hla', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'hmjc', 'total_imports_90d': 135, 'successful_imports_90d': 135, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'hvl', 'total_imports_90d': 7, 'successful_imports_90d': 5, 'import_success_rate': 0.7143, 'last_import_had_errors': False},
    {'org_shortname': 'hvusa', 'total_imports_90d': 13, 'successful_imports_90d': 13, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'ih', 'total_imports_90d': 878, 'successful_imports_90d': 876, 'import_success_rate': 0.9977, 'last_import_had_errors': False},
    {'org_shortname': 'ihm', 'total_imports_90d': 9, 'successful_imports_90d': 9, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'ihw', 'total_imports_90d': 839, 'successful_imports_90d': 829, 'import_success_rate': 0.9881, 'last_import_had_errors': False},
    {'org_shortname': 'jc', 'total_imports_90d': 124, 'successful_imports_90d': 118, 'import_success_rate': 0.9516, 'last_import_had_errors': False},
    {'org_shortname': 'jcsa', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'jcusa', 'total_imports_90d': 155, 'successful_imports_90d': 150, 'import_success_rate': 0.9677, 'last_import_had_errors': False},
    {'org_shortname': 'jgw', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'jyc', 'total_imports_90d': 217, 'successful_imports_90d': 106, 'import_success_rate': 0.4885, 'last_import_had_errors': False},
    {'org_shortname': 'kal', 'total_imports_90d': 334, 'successful_imports_90d': 244, 'import_success_rate': 0.7305, 'last_import_had_errors': False},
    {'org_shortname': 'khl', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'ki', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'kii', 'total_imports_90d': 284, 'successful_imports_90d': 188, 'import_success_rate': 0.662, 'last_import_had_errors': True},
    {'org_shortname': 'kkc', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'kl', 'total_imports_90d': 1, 'successful_imports_90d': 1, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'kll', 'total_imports_90d': 351, 'successful_imports_90d': 309, 'import_success_rate': 0.8803, 'last_import_had_errors': False},
    {'org_shortname': 'krb', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'lcf', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'libco', 'total_imports_90d': 42, 'successful_imports_90d': 24, 'import_success_rate': 0.5714, 'last_import_had_errors': False},
    {'org_shortname': 'lpf', 'total_imports_90d': 815, 'successful_imports_90d': 656, 'import_success_rate': 0.8049, 'last_import_had_errors': False},
    {'org_shortname': 'lss', 'total_imports_90d': 700, 'successful_imports_90d': 697, 'import_success_rate': 0.9957, 'last_import_had_errors': False},
    {'org_shortname': 'luc', 'total_imports_90d': 14, 'successful_imports_90d': 9, 'import_success_rate': 0.6429, 'last_import_had_errors': True},
    {'org_shortname': 'mah', 'total_imports_90d': 238, 'successful_imports_90d': 155, 'import_success_rate': 0.6513, 'last_import_had_errors': False},
    {'org_shortname': 'mali', 'total_imports_90d': 176, 'successful_imports_90d': 121, 'import_success_rate': 0.6875, 'last_import_had_errors': False},
    {'org_shortname': 'mfc', 'total_imports_90d': 14, 'successful_imports_90d': 8, 'import_success_rate': 0.5714, 'last_import_had_errors': False},
    {'org_shortname': 'mfl', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'mh', 'total_imports_90d': 357, 'successful_imports_90d': 207, 'import_success_rate': 0.5798, 'last_import_had_errors': True},
    {'org_shortname': 'mhc', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'ml', 'total_imports_90d': 96, 'successful_imports_90d': 96, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'mlc', 'total_imports_90d': 8, 'successful_imports_90d': 8, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'mlg', 'total_imports_90d': 148, 'successful_imports_90d': 55, 'import_success_rate': 0.3716, 'last_import_had_errors': True},
    {'org_shortname': 'mli', 'total_imports_90d': 293, 'successful_imports_90d': 284, 'import_success_rate': 0.9693, 'last_import_had_errors': False},
    {'org_shortname': 'mpc', 'total_imports_90d': 606, 'successful_imports_90d': 606, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'ol', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'pf', 'total_imports_90d': 501, 'successful_imports_90d': 436, 'import_success_rate': 0.8703, 'last_import_had_errors': False},
    {'org_shortname': 'pcl', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': True},
    {'org_shortname': 'prog', 'total_imports_90d': 13, 'successful_imports_90d': 9, 'import_success_rate': 0.6923, 'last_import_had_errors': False},
    {'org_shortname': 'pw', 'total_imports_90d': 183, 'successful_imports_90d': 182, 'import_success_rate': 0.9945, 'last_import_had_errors': False},
    {'org_shortname': 'rac', 'total_imports_90d': 182, 'successful_imports_90d': 179, 'import_success_rate': 0.9835, 'last_import_had_errors': False},
    {'org_shortname': 'rf', 'total_imports_90d': 299, 'successful_imports_90d': 106, 'import_success_rate': 0.3545, 'last_import_had_errors': False},
    {'org_shortname': 'ril', 'total_imports_90d': 125, 'successful_imports_90d': 88, 'import_success_rate': 0.704, 'last_import_had_errors': False},
    {'org_shortname': 'rw', 'total_imports_90d': 143, 'successful_imports_90d': 138, 'import_success_rate': 0.965, 'last_import_had_errors': False},
    {'org_shortname': 'sarreid', 'total_imports_90d': 412, 'successful_imports_90d': 407, 'import_success_rate': 0.9879, 'last_import_had_errors': False},
    {'org_shortname': 'sbl', 'total_imports_90d': 146, 'successful_imports_90d': 51, 'import_success_rate': 0.3493, 'last_import_had_errors': True},
    {'org_shortname': 'sbmh', 'total_imports_90d': 79, 'successful_imports_90d': 16, 'import_success_rate': 0.2025, 'last_import_had_errors': True},
    {'org_shortname': 'sc', 'total_imports_90d': 1089, 'successful_imports_90d': 1077, 'import_success_rate': 0.989, 'last_import_had_errors': False},
    {'org_shortname': 'sca', 'total_imports_90d': 5, 'successful_imports_90d': 5, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'sccon', 'total_imports_90d': 1292, 'successful_imports_90d': 1284, 'import_success_rate': 0.9938, 'last_import_had_errors': False},
    {'org_shortname': 'sci', 'total_imports_90d': 1104, 'successful_imports_90d': 1097, 'import_success_rate': 0.9937, 'last_import_had_errors': False},
    {'org_shortname': 'scw', 'total_imports_90d': 1338, 'successful_imports_90d': 1327, 'import_success_rate': 0.9918, 'last_import_had_errors': False},
    {'org_shortname': 'sgl', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': True},
    {'org_shortname': 'shl', 'total_imports_90d': 305, 'successful_imports_90d': 223, 'import_success_rate': 0.7311, 'last_import_had_errors': True},
    {'org_shortname': 'sic', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'sl', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'sp', 'total_imports_90d': 123, 'successful_imports_90d': 64, 'import_success_rate': 0.5203, 'last_import_had_errors': True},
    {'org_shortname': 'ssi', 'total_imports_90d': 180, 'successful_imports_90d': 179, 'import_success_rate': 0.9944, 'last_import_had_errors': False},
    {'org_shortname': 'st', 'total_imports_90d': 322, 'successful_imports_90d': 322, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'swc', 'total_imports_90d': 297, 'successful_imports_90d': 297, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'ta', 'total_imports_90d': 246, 'successful_imports_90d': 237, 'import_success_rate': 0.9634, 'last_import_had_errors': False},
    {'org_shortname': 'tam', 'total_imports_90d': 121, 'successful_imports_90d': 112, 'import_success_rate': 0.9256, 'last_import_had_errors': False},
    {'org_shortname': 'tft', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'tl', 'total_imports_90d': 5, 'successful_imports_90d': 3, 'import_success_rate': 0.6, 'last_import_had_errors': False},
    {'org_shortname': 'tla', 'total_imports_90d': 567, 'successful_imports_90d': 339, 'import_success_rate': 0.5979, 'last_import_had_errors': False},
    {'org_shortname': 'ttf', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'ufi', 'total_imports_90d': 368, 'successful_imports_90d': 360, 'import_success_rate': 0.9783, 'last_import_had_errors': False},
    {'org_shortname': 'uhc', 'total_imports_90d': 5000, 'successful_imports_90d': 5000, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'vce', 'total_imports_90d': 212, 'successful_imports_90d': 203, 'import_success_rate': 0.9575, 'last_import_had_errors': False},
    {'org_shortname': 'vcg', 'total_imports_90d': 226, 'successful_imports_90d': 124, 'import_success_rate': 0.5487, 'last_import_had_errors': True},
    {'org_shortname': 'vic', 'total_imports_90d': 114, 'successful_imports_90d': 106, 'import_success_rate': 0.9298, 'last_import_had_errors': False},
    {'org_shortname': 'vl', 'total_imports_90d': 294, 'successful_imports_90d': 195, 'import_success_rate': 0.6633, 'last_import_had_errors': False},
    {'org_shortname': 'wac', 'total_imports_90d': 155, 'successful_imports_90d': 146, 'import_success_rate': 0.9419, 'last_import_had_errors': False},
    {'org_shortname': 'wag', 'total_imports_90d': 64, 'successful_imports_90d': 40, 'import_success_rate': 0.625, 'last_import_had_errors': False},
    {'org_shortname': 'wwjc', 'total_imports_90d': 1183, 'successful_imports_90d': 1153, 'import_success_rate': 0.9746, 'last_import_had_errors': False},
    {'org_shortname': 'yw', 'total_imports_90d': 9, 'successful_imports_90d': 5, 'import_success_rate': 0.5556, 'last_import_had_errors': False},
    # Non-MAL orgs that might be in eligible universe
    {'org_shortname': 'elk', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': True},
    {'org_shortname': 'bc', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': True},
    {'org_shortname': 'ebc', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': True},
    {'org_shortname': 'dpl', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': True},
    {'org_shortname': 'hatl', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'hla', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'hcan', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': True},
    {'org_shortname': 'kkc', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'luc', 'total_imports_90d': 14, 'successful_imports_90d': 9, 'import_success_rate': 0.6429, 'last_import_had_errors': True},
    {'org_shortname': 'pcl', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': True},
    {'org_shortname': 'sci', 'total_imports_90d': 1104, 'successful_imports_90d': 1097, 'import_success_rate': 0.9937, 'last_import_had_errors': False},
    {'org_shortname': 'swc', 'total_imports_90d': 297, 'successful_imports_90d': 297, 'import_success_rate': 1.0, 'last_import_had_errors': False},
    {'org_shortname': 'sic', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'bobo', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'ati', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
    {'org_shortname': 'bi', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': True},
    {'org_shortname': 'bei', 'total_imports_90d': 0, 'successful_imports_90d': 0, 'import_success_rate': None, 'last_import_had_errors': False},
]
# Deduplicate (in case of duplicates)
imp_df = pd.DataFrame(imp_data).drop_duplicates(subset=['org_shortname'], keep='first')
imp_df.to_csv(CACHE_DIR / "pg_imp.csv", index=False)
print(f"pg_imp.csv: {len(imp_df)} rows")

# ---- pg_ord ----
ord_data = [
    {'org_shortname': 'aa', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'abol', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': False},
    {'org_shortname': 'acsd', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'afx', 'orders_90d': 60, 'orders_prior_90d': 1, 'ipad_orders_90d': 60, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'ah', 'orders_90d': 272, 'orders_prior_90d': 219, 'ipad_orders_90d': 208, 'online_orders_90d': 64, 'orders_exist_any_time': True},
    {'org_shortname': 'ali', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'all', 'orders_90d': 12, 'orders_prior_90d': 7, 'ipad_orders_90d': 12, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'am', 'orders_90d': 20, 'orders_prior_90d': 34, 'ipad_orders_90d': 20, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'ap', 'orders_90d': 8, 'orders_prior_90d': 6, 'ipad_orders_90d': 1, 'online_orders_90d': 7, 'orders_exist_any_time': True},
    {'org_shortname': 'arl', 'orders_90d': 113, 'orders_prior_90d': 61, 'ipad_orders_90d': 113, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'art', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'asi', 'orders_90d': 1971, 'orders_prior_90d': 2420, 'ipad_orders_90d': 1157, 'online_orders_90d': 814, 'orders_exist_any_time': True},
    {'org_shortname': 'ati', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'bc', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'bcf', 'orders_90d': 755, 'orders_prior_90d': 533, 'ipad_orders_90d': 367, 'online_orders_90d': 388, 'orders_exist_any_time': True},
    {'org_shortname': 'bei', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'bi', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'big', 'orders_90d': 0, 'orders_prior_90d': 6, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'blh', 'orders_90d': 2, 'orders_prior_90d': 14, 'ipad_orders_90d': 0, 'online_orders_90d': 2, 'orders_exist_any_time': True},
    {'org_shortname': 'bmc', 'orders_90d': 0, 'orders_prior_90d': 28, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'bobo', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'bp', 'orders_90d': 3, 'orders_prior_90d': 0, 'ipad_orders_90d': 3, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'bri', 'orders_90d': 718, 'orders_prior_90d': 781, 'ipad_orders_90d': 57, 'online_orders_90d': 661, 'orders_exist_any_time': True},
    {'org_shortname': 'bsc', 'orders_90d': 2, 'orders_prior_90d': 12, 'ipad_orders_90d': 2, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'cc', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'cci', 'orders_90d': 985, 'orders_prior_90d': 861, 'ipad_orders_90d': 985, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'cf', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': False},
    {'org_shortname': 'cfg', 'orders_90d': 114, 'orders_prior_90d': 120, 'ipad_orders_90d': 58, 'online_orders_90d': 56, 'orders_exist_any_time': True},
    {'org_shortname': 'cl', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'clc', 'orders_90d': 260, 'orders_prior_90d': 3, 'ipad_orders_90d': 260, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'clli', 'orders_90d': 167, 'orders_prior_90d': 9, 'ipad_orders_90d': 167, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'clm', 'orders_90d': 108, 'orders_prior_90d': 20, 'ipad_orders_90d': 108, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'cst', 'orders_90d': 21, 'orders_prior_90d': 0, 'ipad_orders_90d': 21, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'da', 'orders_90d': 1067, 'orders_prior_90d': 933, 'ipad_orders_90d': 1067, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'dals', 'orders_90d': 2, 'orders_prior_90d': 0, 'ipad_orders_90d': 2, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'dccl', 'orders_90d': 63, 'orders_prior_90d': 66, 'ipad_orders_90d': 61, 'online_orders_90d': 2, 'orders_exist_any_time': True},
    {'org_shortname': 'df', 'orders_90d': 2, 'orders_prior_90d': 2, 'ipad_orders_90d': 2, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'dpl', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'dri', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'dws', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'ebc', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'eglo', 'orders_90d': 42, 'orders_prior_90d': 11, 'ipad_orders_90d': 42, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'eglo_can', 'orders_90d': 33, 'orders_prior_90d': 2, 'ipad_orders_90d': 33, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'el', 'orders_90d': 131, 'orders_prior_90d': 9, 'ipad_orders_90d': 131, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'eli', 'orders_90d': 107, 'orders_prior_90d': 77, 'ipad_orders_90d': 103, 'online_orders_90d': 4, 'orders_exist_any_time': True},
    {'org_shortname': 'elk', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'et2', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'etl', 'orders_90d': 149, 'orders_prior_90d': 153, 'ipad_orders_90d': 149, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'fal', 'orders_90d': 587, 'orders_prior_90d': 576, 'ipad_orders_90d': 587, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'fc', 'orders_90d': 860, 'orders_prior_90d': 774, 'ipad_orders_90d': 538, 'online_orders_90d': 322, 'orders_exist_any_time': True},
    {'org_shortname': 'fcc', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'fms', 'orders_90d': 512, 'orders_prior_90d': 192, 'ipad_orders_90d': 512, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'frh', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'fsf', 'orders_90d': 1997, 'orders_prior_90d': 1759, 'ipad_orders_90d': 208, 'online_orders_90d': 1789, 'orders_exist_any_time': True},
    {'org_shortname': 'gb', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'gc', 'orders_90d': 349, 'orders_prior_90d': 351, 'ipad_orders_90d': 233, 'online_orders_90d': 116, 'orders_exist_any_time': True},
    {'org_shortname': 'gcl', 'orders_90d': 70, 'orders_prior_90d': 58, 'ipad_orders_90d': 70, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'gg', 'orders_90d': 369, 'orders_prior_90d': 156, 'ipad_orders_90d': 369, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'gh', 'orders_90d': 3741, 'orders_prior_90d': 3026, 'ipad_orders_90d': 2458, 'online_orders_90d': 1283, 'orders_exist_any_time': True},
    {'org_shortname': 'gl', 'orders_90d': 81, 'orders_prior_90d': 47, 'ipad_orders_90d': 12, 'online_orders_90d': 69, 'orders_exist_any_time': True},
    {'org_shortname': 'gsa', 'orders_90d': 9, 'orders_prior_90d': 9, 'ipad_orders_90d': 9, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'hatl', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'hcan', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': False},
    {'org_shortname': 'heb', 'orders_90d': 112, 'orders_prior_90d': 63, 'ipad_orders_90d': 112, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'hf', 'orders_90d': 16, 'orders_prior_90d': 53, 'ipad_orders_90d': 16, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'hfg', 'orders_90d': 578, 'orders_prior_90d': 358, 'ipad_orders_90d': 578, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'hh', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': False},
    {'org_shortname': 'hla', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'hmjc', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'hvl', 'orders_90d': 1, 'orders_prior_90d': 0, 'ipad_orders_90d': 1, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'hvusa', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': False},
    {'org_shortname': 'ih', 'orders_90d': 764, 'orders_prior_90d': 828, 'ipad_orders_90d': 764, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'ihm', 'orders_90d': 1, 'orders_prior_90d': 2, 'ipad_orders_90d': 1, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'ihw', 'orders_90d': 425, 'orders_prior_90d': 387, 'ipad_orders_90d': 425, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'jc', 'orders_90d': 0, 'orders_prior_90d': 37, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'jcsa', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'jcusa', 'orders_90d': 39, 'orders_prior_90d': 94, 'ipad_orders_90d': 39, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'jgw', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'jyc', 'orders_90d': 2044, 'orders_prior_90d': 1935, 'ipad_orders_90d': 1036, 'online_orders_90d': 1008, 'orders_exist_any_time': True},
    {'org_shortname': 'kal', 'orders_90d': 83, 'orders_prior_90d': 38, 'ipad_orders_90d': 74, 'online_orders_90d': 9, 'orders_exist_any_time': True},
    {'org_shortname': 'khl', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'ki', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'kii', 'orders_90d': 661, 'orders_prior_90d': 674, 'ipad_orders_90d': 647, 'online_orders_90d': 14, 'orders_exist_any_time': True},
    {'org_shortname': 'kkc', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'kl', 'orders_90d': 120, 'orders_prior_90d': 3, 'ipad_orders_90d': 120, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'kll', 'orders_90d': 128, 'orders_prior_90d': 46, 'ipad_orders_90d': 71, 'online_orders_90d': 57, 'orders_exist_any_time': True},
    {'org_shortname': 'krb', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'lcf', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'libco', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': False},
    {'org_shortname': 'lpf', 'orders_90d': 438, 'orders_prior_90d': 450, 'ipad_orders_90d': 189, 'online_orders_90d': 249, 'orders_exist_any_time': True},
    {'org_shortname': 'lss', 'orders_90d': 67, 'orders_prior_90d': 2, 'ipad_orders_90d': 67, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'luc', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'mah', 'orders_90d': 197, 'orders_prior_90d': 170, 'ipad_orders_90d': 159, 'online_orders_90d': 38, 'orders_exist_any_time': True},
    {'org_shortname': 'mali', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': False},
    {'org_shortname': 'mfc', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'mfl', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'mh', 'orders_90d': 66, 'orders_prior_90d': 50, 'ipad_orders_90d': 66, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'mhc', 'orders_90d': 0, 'orders_prior_90d': 82, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'ml', 'orders_90d': 35, 'orders_prior_90d': 1, 'ipad_orders_90d': 35, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'mlc', 'orders_90d': 73, 'orders_prior_90d': 12, 'ipad_orders_90d': 73, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'mlg', 'orders_90d': 124, 'orders_prior_90d': 3, 'ipad_orders_90d': 124, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'mli', 'orders_90d': 78, 'orders_prior_90d': 2, 'ipad_orders_90d': 78, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'mpc', 'orders_90d': 1206, 'orders_prior_90d': 1561, 'ipad_orders_90d': 1133, 'online_orders_90d': 73, 'orders_exist_any_time': True},
    {'org_shortname': 'ol', 'orders_90d': 0, 'orders_prior_90d': 34, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'pf', 'orders_90d': 663, 'orders_prior_90d': 573, 'ipad_orders_90d': 663, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'pcl', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'prog', 'orders_90d': 71, 'orders_prior_90d': 2, 'ipad_orders_90d': 71, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'pw', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'rac', 'orders_90d': 141, 'orders_prior_90d': 130, 'ipad_orders_90d': 141, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'rf', 'orders_90d': 15, 'orders_prior_90d': 17, 'ipad_orders_90d': 15, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'ril', 'orders_90d': 335, 'orders_prior_90d': 173, 'ipad_orders_90d': 296, 'online_orders_90d': 39, 'orders_exist_any_time': True},
    {'org_shortname': 'rw', 'orders_90d': 2243, 'orders_prior_90d': 2148, 'ipad_orders_90d': 2243, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'sarreid', 'orders_90d': 119, 'orders_prior_90d': 168, 'ipad_orders_90d': 119, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'sbl', 'orders_90d': 104, 'orders_prior_90d': 16, 'ipad_orders_90d': 104, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'sbmh', 'orders_90d': 845, 'orders_prior_90d': 728, 'ipad_orders_90d': 511, 'online_orders_90d': 334, 'orders_exist_any_time': True},
    {'org_shortname': 'sc', 'orders_90d': 6839, 'orders_prior_90d': 6323, 'ipad_orders_90d': 6839, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'sca', 'orders_90d': 86, 'orders_prior_90d': 109, 'ipad_orders_90d': 86, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'sccon', 'orders_90d': 2166, 'orders_prior_90d': 1274, 'ipad_orders_90d': 2135, 'online_orders_90d': 31, 'orders_exist_any_time': True},
    {'org_shortname': 'sci', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'scw', 'orders_90d': 3570, 'orders_prior_90d': 2042, 'ipad_orders_90d': 2682, 'online_orders_90d': 888, 'orders_exist_any_time': True},
    {'org_shortname': 'sgl', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'shl', 'orders_90d': 336, 'orders_prior_90d': 65, 'ipad_orders_90d': 252, 'online_orders_90d': 84, 'orders_exist_any_time': True},
    {'org_shortname': 'sic', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'sl', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'sp', 'orders_90d': 86, 'orders_prior_90d': 53, 'ipad_orders_90d': 86, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'ssi', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'st', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'swc', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'ta', 'orders_90d': 461, 'orders_prior_90d': 526, 'ipad_orders_90d': 459, 'online_orders_90d': 2, 'orders_exist_any_time': True},
    {'org_shortname': 'tam', 'orders_90d': 120, 'orders_prior_90d': 112, 'ipad_orders_90d': 120, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'tft', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'tl', 'orders_90d': 1, 'orders_prior_90d': 0, 'ipad_orders_90d': 1, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'tla', 'orders_90d': 155, 'orders_prior_90d': 26, 'ipad_orders_90d': 155, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'ttf', 'orders_90d': 0, 'orders_prior_90d': 0, 'ipad_orders_90d': 0, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'ufi', 'orders_90d': 496, 'orders_prior_90d': 532, 'ipad_orders_90d': 496, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'uhc', 'orders_90d': 924, 'orders_prior_90d': 946, 'ipad_orders_90d': 924, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'vce', 'orders_90d': 18, 'orders_prior_90d': 14, 'ipad_orders_90d': 18, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'vcg', 'orders_90d': 256, 'orders_prior_90d': 134, 'ipad_orders_90d': 256, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'vic', 'orders_90d': 22, 'orders_prior_90d': 20, 'ipad_orders_90d': 0, 'online_orders_90d': 22, 'orders_exist_any_time': True},
    {'org_shortname': 'vl', 'orders_90d': 79, 'orders_prior_90d': 6, 'ipad_orders_90d': 79, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'wac', 'orders_90d': 971, 'orders_prior_90d': 258, 'ipad_orders_90d': 971, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'wag', 'orders_90d': 900, 'orders_prior_90d': 772, 'ipad_orders_90d': 900, 'online_orders_90d': 0, 'orders_exist_any_time': True},
    {'org_shortname': 'wwjc', 'orders_90d': 1797, 'orders_prior_90d': 1532, 'ipad_orders_90d': 367, 'online_orders_90d': 1430, 'orders_exist_any_time': True},
    {'org_shortname': 'yw', 'orders_90d': 6, 'orders_prior_90d': 36, 'ipad_orders_90d': 6, 'online_orders_90d': 0, 'orders_exist_any_time': True},
]
pd.DataFrame(ord_data).drop_duplicates(subset=['org_shortname'], keep='first').to_csv(CACHE_DIR / "pg_ord.csv", index=False)
print(f"pg_ord.csv: {len(ord_data)} rows")

# ---- pg_users ----
users_data = [
    {'org_shortname': 'aa', 'total_users': 7}, {'org_shortname': 'abol', 'total_users': 30},
    {'org_shortname': 'acsd', 'total_users': 13}, {'org_shortname': 'afx', 'total_users': 76},
    {'org_shortname': 'ah', 'total_users': 1826}, {'org_shortname': 'ali', 'total_users': 248},
    {'org_shortname': 'all', 'total_users': 74}, {'org_shortname': 'am', 'total_users': 28},
    {'org_shortname': 'ap', 'total_users': 1228}, {'org_shortname': 'arl', 'total_users': 71},
    {'org_shortname': 'art', 'total_users': 58}, {'org_shortname': 'asi', 'total_users': 292},
    {'org_shortname': 'ati', 'total_users': 60}, {'org_shortname': 'bc', 'total_users': 16},
    {'org_shortname': 'bcf', 'total_users': 1389}, {'org_shortname': 'bei', 'total_users': 15},
    {'org_shortname': 'bi', 'total_users': 17}, {'org_shortname': 'big', 'total_users': 106},
    {'org_shortname': 'blh', 'total_users': 3610}, {'org_shortname': 'bmc', 'total_users': 6567},
    {'org_shortname': 'bobo', 'total_users': 75}, {'org_shortname': 'bp', 'total_users': 98},
    {'org_shortname': 'bri', 'total_users': 1290}, {'org_shortname': 'bsc', 'total_users': 29},
    {'org_shortname': 'cc', 'total_users': 31}, {'org_shortname': 'cci', 'total_users': 105},
    {'org_shortname': 'cf', 'total_users': 117}, {'org_shortname': 'cfg', 'total_users': 1475},
    {'org_shortname': 'cl', 'total_users': 213}, {'org_shortname': 'clc', 'total_users': 1060},
    {'org_shortname': 'clli', 'total_users': 1687}, {'org_shortname': 'clm', 'total_users': 763},
    {'org_shortname': 'cst', 'total_users': 67}, {'org_shortname': 'da', 'total_users': 50},
    {'org_shortname': 'dals', 'total_users': 65}, {'org_shortname': 'dccl', 'total_users': 29},
    {'org_shortname': 'df', 'total_users': 49}, {'org_shortname': 'dpl', 'total_users': 12},
    {'org_shortname': 'dri', 'total_users': 18}, {'org_shortname': 'dws', 'total_users': 45},
    {'org_shortname': 'ebc', 'total_users': 27}, {'org_shortname': 'eglo', 'total_users': 62},
    {'org_shortname': 'eglo_can', 'total_users': 28}, {'org_shortname': 'el', 'total_users': 330},
    {'org_shortname': 'eli', 'total_users': 1477}, {'org_shortname': 'elk', 'total_users': 137},
    {'org_shortname': 'et2', 'total_users': 94}, {'org_shortname': 'etl', 'total_users': 26},
    {'org_shortname': 'fal', 'total_users': 62}, {'org_shortname': 'fc', 'total_users': 9162},
    {'org_shortname': 'fcc', 'total_users': 35}, {'org_shortname': 'fms', 'total_users': 221},
    {'org_shortname': 'frh', 'total_users': 486}, {'org_shortname': 'fsf', 'total_users': 719},
    {'org_shortname': 'gb', 'total_users': 20}, {'org_shortname': 'gc', 'total_users': 328},
    {'org_shortname': 'gcl', 'total_users': 41}, {'org_shortname': 'gg', 'total_users': 54},
    {'org_shortname': 'gh', 'total_users': 7892}, {'org_shortname': 'gl', 'total_users': 563},
    {'org_shortname': 'gsa', 'total_users': 53}, {'org_shortname': 'hatl', 'total_users': 14},
    {'org_shortname': 'hcan', 'total_users': 11}, {'org_shortname': 'heb', 'total_users': 114},
    {'org_shortname': 'hf', 'total_users': 71}, {'org_shortname': 'hfg', 'total_users': 203},
    {'org_shortname': 'hh', 'total_users': 86}, {'org_shortname': 'hla', 'total_users': 16},
    {'org_shortname': 'hmjc', 'total_users': 158}, {'org_shortname': 'hvl', 'total_users': 190},
    {'org_shortname': 'hvusa', 'total_users': 10}, {'org_shortname': 'ih', 'total_users': 58},
    {'org_shortname': 'ihm', 'total_users': 56}, {'org_shortname': 'ihw', 'total_users': 64},
    {'org_shortname': 'jc', 'total_users': 59}, {'org_shortname': 'jcsa', 'total_users': 20},
    {'org_shortname': 'jcusa', 'total_users': 2555}, {'org_shortname': 'jgw', 'total_users': 39},
    {'org_shortname': 'jyc', 'total_users': 15840}, {'org_shortname': 'kal', 'total_users': 1645},
    {'org_shortname': 'khl', 'total_users': 1571}, {'org_shortname': 'ki', 'total_users': 38},
    {'org_shortname': 'kii', 'total_users': 108}, {'org_shortname': 'kkc', 'total_users': 89},
    {'org_shortname': 'kl', 'total_users': 129}, {'org_shortname': 'kll', 'total_users': 914},
    {'org_shortname': 'krb', 'total_users': 39}, {'org_shortname': 'lcf', 'total_users': 8},
    {'org_shortname': 'libco', 'total_users': 2}, {'org_shortname': 'lpf', 'total_users': 2453},
    {'org_shortname': 'lss', 'total_users': 29}, {'org_shortname': 'luc', 'total_users': 29},
    {'org_shortname': 'mah', 'total_users': 363}, {'org_shortname': 'mali', 'total_users': 10},
    {'org_shortname': 'mfc', 'total_users': 574}, {'org_shortname': 'mfl', 'total_users': 4},
    {'org_shortname': 'mh', 'total_users': 104}, {'org_shortname': 'mhc', 'total_users': 57},
    {'org_shortname': 'ml', 'total_users': 138}, {'org_shortname': 'mlc', 'total_users': 65},
    {'org_shortname': 'mlg', 'total_users': 109}, {'org_shortname': 'mli', 'total_users': 95},
    {'org_shortname': 'mpc', 'total_users': 251}, {'org_shortname': 'ol', 'total_users': 26},
    {'org_shortname': 'pf', 'total_users': 196}, {'org_shortname': 'pcl', 'total_users': 60},
    {'org_shortname': 'prog', 'total_users': 110}, {'org_shortname': 'pw', 'total_users': 50},
    {'org_shortname': 'rac', 'total_users': 52}, {'org_shortname': 'rf', 'total_users': 63},
    {'org_shortname': 'ril', 'total_users': 262}, {'org_shortname': 'rw', 'total_users': 101},
    {'org_shortname': 'sarreid', 'total_users': 142}, {'org_shortname': 'sbl', 'total_users': 142},
    {'org_shortname': 'sbmh', 'total_users': 3377}, {'org_shortname': 'sc', 'total_users': 156},
    {'org_shortname': 'sca', 'total_users': 44}, {'org_shortname': 'sccon', 'total_users': 1169},
    {'org_shortname': 'sci', 'total_users': 38}, {'org_shortname': 'scw', 'total_users': 4469},
    {'org_shortname': 'sgl', 'total_users': 3}, {'org_shortname': 'shl', 'total_users': 2082},
    {'org_shortname': 'sic', 'total_users': 3}, {'org_shortname': 'sl', 'total_users': 99},
    {'org_shortname': 'sp', 'total_users': 20}, {'org_shortname': 'ssi', 'total_users': 51},
    {'org_shortname': 'st', 'total_users': 26}, {'org_shortname': 'swc', 'total_users': 37},
    {'org_shortname': 'ta', 'total_users': 515}, {'org_shortname': 'tam', 'total_users': 33},
    {'org_shortname': 'tft', 'total_users': 28}, {'org_shortname': 'tl', 'total_users': 221},
    {'org_shortname': 'tla', 'total_users': 210}, {'org_shortname': 'ttf', 'total_users': 29},
    {'org_shortname': 'ufi', 'total_users': 127}, {'org_shortname': 'uhc', 'total_users': 25},
    {'org_shortname': 'vce', 'total_users': 39}, {'org_shortname': 'vcg', 'total_users': 177},
    {'org_shortname': 'vic', 'total_users': 330}, {'org_shortname': 'vl', 'total_users': 105},
    {'org_shortname': 'wac', 'total_users': 170}, {'org_shortname': 'wag', 'total_users': 103},
    {'org_shortname': 'wwjc', 'total_users': 20233}, {'org_shortname': 'yw', 'total_users': 36},
]
pd.DataFrame(users_data).to_csv(CACHE_DIR / "pg_users.csv", index=False)
print(f"pg_users.csv: {len(users_data)} rows")

# ---- pg_stacks ----
stacks_data = [
    {'org_shortname': 'aa', 'smart_stack_count': 15}, {'org_shortname': 'abol', 'smart_stack_count': 1},
    {'org_shortname': 'acsd', 'smart_stack_count': 0}, {'org_shortname': 'afx', 'smart_stack_count': 11},
    {'org_shortname': 'ah', 'smart_stack_count': 21}, {'org_shortname': 'ali', 'smart_stack_count': 17},
    {'org_shortname': 'all', 'smart_stack_count': 1}, {'org_shortname': 'am', 'smart_stack_count': 10},
    {'org_shortname': 'ap', 'smart_stack_count': 47}, {'org_shortname': 'arl', 'smart_stack_count': 0},
    {'org_shortname': 'art', 'smart_stack_count': 61}, {'org_shortname': 'asi', 'smart_stack_count': 12},
    {'org_shortname': 'ati', 'smart_stack_count': 45}, {'org_shortname': 'bc', 'smart_stack_count': 8},
    {'org_shortname': 'bcf', 'smart_stack_count': 123}, {'org_shortname': 'bei', 'smart_stack_count': 5},
    {'org_shortname': 'bi', 'smart_stack_count': 1}, {'org_shortname': 'big', 'smart_stack_count': 26},
    {'org_shortname': 'blh', 'smart_stack_count': 0}, {'org_shortname': 'bmc', 'smart_stack_count': 37},
    {'org_shortname': 'bobo', 'smart_stack_count': 3}, {'org_shortname': 'bp', 'smart_stack_count': 6},
    {'org_shortname': 'bri', 'smart_stack_count': 19}, {'org_shortname': 'bsc', 'smart_stack_count': 77},
    {'org_shortname': 'cc', 'smart_stack_count': 37}, {'org_shortname': 'cci', 'smart_stack_count': 7},
    {'org_shortname': 'cf', 'smart_stack_count': 15}, {'org_shortname': 'cfg', 'smart_stack_count': 10},
    {'org_shortname': 'cl', 'smart_stack_count': 5}, {'org_shortname': 'clc', 'smart_stack_count': 16},
    {'org_shortname': 'clli', 'smart_stack_count': 38}, {'org_shortname': 'clm', 'smart_stack_count': 20},
    {'org_shortname': 'cst', 'smart_stack_count': 13}, {'org_shortname': 'da', 'smart_stack_count': 39},
    {'org_shortname': 'dals', 'smart_stack_count': 2}, {'org_shortname': 'dccl', 'smart_stack_count': 12},
    {'org_shortname': 'df', 'smart_stack_count': 5}, {'org_shortname': 'dpl', 'smart_stack_count': 21},
    {'org_shortname': 'dri', 'smart_stack_count': 4}, {'org_shortname': 'dws', 'smart_stack_count': 8},
    {'org_shortname': 'ebc', 'smart_stack_count': 34}, {'org_shortname': 'eglo', 'smart_stack_count': 9},
    {'org_shortname': 'eglo_can', 'smart_stack_count': 6}, {'org_shortname': 'el', 'smart_stack_count': 11},
    {'org_shortname': 'eli', 'smart_stack_count': 18}, {'org_shortname': 'elk', 'smart_stack_count': 36},
    {'org_shortname': 'et2', 'smart_stack_count': 22}, {'org_shortname': 'etl', 'smart_stack_count': 5},
    {'org_shortname': 'fal', 'smart_stack_count': 2}, {'org_shortname': 'fc', 'smart_stack_count': 8},
    {'org_shortname': 'fcc', 'smart_stack_count': 18}, {'org_shortname': 'fms', 'smart_stack_count': 29},
    {'org_shortname': 'frh', 'smart_stack_count': 14}, {'org_shortname': 'fsf', 'smart_stack_count': 4},
    {'org_shortname': 'gb', 'smart_stack_count': 0}, {'org_shortname': 'gc', 'smart_stack_count': 1},
    {'org_shortname': 'gcl', 'smart_stack_count': 0}, {'org_shortname': 'gg', 'smart_stack_count': 21},
    {'org_shortname': 'gh', 'smart_stack_count': 2}, {'org_shortname': 'gl', 'smart_stack_count': 10},
    {'org_shortname': 'gsa', 'smart_stack_count': 19}, {'org_shortname': 'hatl', 'smart_stack_count': 32},
    {'org_shortname': 'hcan', 'smart_stack_count': 32}, {'org_shortname': 'heb', 'smart_stack_count': 255},
    {'org_shortname': 'hf', 'smart_stack_count': 23}, {'org_shortname': 'hfg', 'smart_stack_count': 7},
    {'org_shortname': 'hh', 'smart_stack_count': 8}, {'org_shortname': 'hla', 'smart_stack_count': 28},
    {'org_shortname': 'hmjc', 'smart_stack_count': 2}, {'org_shortname': 'hvl', 'smart_stack_count': 20},
    {'org_shortname': 'hvusa', 'smart_stack_count': 0}, {'org_shortname': 'ih', 'smart_stack_count': 11},
    {'org_shortname': 'ihm', 'smart_stack_count': 0}, {'org_shortname': 'ihw', 'smart_stack_count': 7},
    {'org_shortname': 'jc', 'smart_stack_count': 28}, {'org_shortname': 'jcsa', 'smart_stack_count': 44},
    {'org_shortname': 'jcusa', 'smart_stack_count': 47}, {'org_shortname': 'jgw', 'smart_stack_count': 22},
    {'org_shortname': 'jyc', 'smart_stack_count': 10}, {'org_shortname': 'kal', 'smart_stack_count': 8},
    {'org_shortname': 'khl', 'smart_stack_count': 13}, {'org_shortname': 'ki', 'smart_stack_count': 3},
    {'org_shortname': 'kii', 'smart_stack_count': 17}, {'org_shortname': 'kkc', 'smart_stack_count': 11},
    {'org_shortname': 'kl', 'smart_stack_count': 1}, {'org_shortname': 'kll', 'smart_stack_count': 20},
    {'org_shortname': 'krb', 'smart_stack_count': 1}, {'org_shortname': 'lcf', 'smart_stack_count': 7},
    {'org_shortname': 'libco', 'smart_stack_count': 1}, {'org_shortname': 'lpf', 'smart_stack_count': 27},
    {'org_shortname': 'lss', 'smart_stack_count': 2}, {'org_shortname': 'luc', 'smart_stack_count': 12},
    {'org_shortname': 'mah', 'smart_stack_count': 5}, {'org_shortname': 'mali', 'smart_stack_count': 0},
    {'org_shortname': 'mfc', 'smart_stack_count': 46}, {'org_shortname': 'mfl', 'smart_stack_count': 22},
    {'org_shortname': 'mh', 'smart_stack_count': 14}, {'org_shortname': 'mhc', 'smart_stack_count': 86},
    {'org_shortname': 'ml', 'smart_stack_count': 45}, {'org_shortname': 'mlc', 'smart_stack_count': 8},
    {'org_shortname': 'mlg', 'smart_stack_count': 9}, {'org_shortname': 'mli', 'smart_stack_count': 41},
    {'org_shortname': 'mpc', 'smart_stack_count': 10}, {'org_shortname': 'ol', 'smart_stack_count': 16},
    {'org_shortname': 'pf', 'smart_stack_count': 28}, {'org_shortname': 'pcl', 'smart_stack_count': 29},
    {'org_shortname': 'prog', 'smart_stack_count': 0}, {'org_shortname': 'pw', 'smart_stack_count': 2},
    {'org_shortname': 'rac', 'smart_stack_count': 15}, {'org_shortname': 'rf', 'smart_stack_count': 19},
    {'org_shortname': 'ril', 'smart_stack_count': 6}, {'org_shortname': 'rw', 'smart_stack_count': 8},
    {'org_shortname': 'sarreid', 'smart_stack_count': 63}, {'org_shortname': 'sbl', 'smart_stack_count': 6},
    {'org_shortname': 'sbmh', 'smart_stack_count': 4}, {'org_shortname': 'sc', 'smart_stack_count': 4},
    {'org_shortname': 'sca', 'smart_stack_count': 16}, {'org_shortname': 'sccon', 'smart_stack_count': 4},
    {'org_shortname': 'sci', 'smart_stack_count': 0}, {'org_shortname': 'scw', 'smart_stack_count': 5},
    {'org_shortname': 'sgl', 'smart_stack_count': 25}, {'org_shortname': 'shl', 'smart_stack_count': 12},
    {'org_shortname': 'sic', 'smart_stack_count': 27}, {'org_shortname': 'sl', 'smart_stack_count': 0},
    {'org_shortname': 'sp', 'smart_stack_count': 0}, {'org_shortname': 'ssi', 'smart_stack_count': 2},
    {'org_shortname': 'st', 'smart_stack_count': 2}, {'org_shortname': 'swc', 'smart_stack_count': 10},
    {'org_shortname': 'ta', 'smart_stack_count': 6}, {'org_shortname': 'tam', 'smart_stack_count': 0},
    {'org_shortname': 'tft', 'smart_stack_count': 0}, {'org_shortname': 'tl', 'smart_stack_count': 7},
    {'org_shortname': 'tla', 'smart_stack_count': 12}, {'org_shortname': 'ttf', 'smart_stack_count': 8},
    {'org_shortname': 'ufi', 'smart_stack_count': 46}, {'org_shortname': 'uhc', 'smart_stack_count': 67},
    {'org_shortname': 'vce', 'smart_stack_count': 7}, {'org_shortname': 'vcg', 'smart_stack_count': 4},
    {'org_shortname': 'vic', 'smart_stack_count': 15}, {'org_shortname': 'vl', 'smart_stack_count': 4},
    {'org_shortname': 'wac', 'smart_stack_count': 11}, {'org_shortname': 'wag', 'smart_stack_count': 22},
    {'org_shortname': 'wwjc', 'smart_stack_count': 81}, {'org_shortname': 'yw', 'smart_stack_count': 0},
]
pd.DataFrame(stacks_data).to_csv(CACHE_DIR / "pg_stacks.csv", index=False)
print(f"pg_stacks.csv: {len(stacks_data)} rows")

# ---- pg_cust (keep from existing cache - Apr 2 data, still valid) ----
# The customer query failed MCP validation, keep Apr 2 cache as-is
print("pg_cust.csv: keeping existing Apr 2 cache (live query unavailable due to MCP validator)")

print("\nAll cache files written successfully.")
